# https://docs.github.com/actions/creating-actions/metadata-syntax-for-github-actions

name: "This repo has x stars y forks action"
description: 'Update repository description to "This repo has x stars y forks".'
author: "Yufan You"

inputs:
  token:
    description: |
      A GitHub Personal Access Token with the public_repo scope.
      GITHUB_TOKEN is not available because it doesn't have enough permission to update the description of the repo.
    required: true
  repo:
    description: The repository to update, in the "<owner>/<name>" format.
    default: ${{ github.repository }}
    required: false
  type:
    description: Which one to update. Either "name" or "description".
    default: description
    required: false
  template:
    description: |
      The repository description. You can use the following place holders:
      - <starCount>:         <the number of stars>
      - <forkCount>:         <the number of forks>
      - <name>:              this-repo-has-<stars>-stars-<forks>-forks
      - <description>:       This repo has <stars> stars <forks> forks
      - <auto>:              <${ inputs.type }>
      - <name-stars>:        this-repo-has-<stars>-stars
      - <description-stars>: This repo has <stars> stars
      - <auto-stars>:        <${ inputs.type }-stars>
      - <name-forks>:        this-repo-has-<forks>-forks
      - <description-forks>: This repo has <forks> forks
      - <auto-forks>:        <${ inputs.type }-forks>
    default: <auto>
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
