name: Build

on:
  push:
    branches:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - run: git diff --exit-code
